<?php
/*
 * (c) 2014, Dmitrijs Balabka
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Amp\AmpBundle\Command;

use Amp\AmpBundle\LoopCallback;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Amp\Loop;

class ServerRunCommand extends Command
{
    protected static $defaultName = 'amp:server:run';

    /** @var LoopCallback */
    private $loopCallback;

    public function __construct(LoopCallback $loopCallback)
    {
        $this->loopCallback = $loopCallback;
        parent::__construct();
    }

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        Loop::run($this->loopCallback);
    }
}
